FROM openjdk:8-oracle

ADD ./threadlocal-pratice/target/threadlocal-pratice-0.0.1-SNAPSHOT.jar /home/project/threadlocal-pratice-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java","-jar","/home/project/threadlocal-pratice-0.0.1-SNAPSHOT.jar"]