FROM openjdk:8-oracle

ENV version=Starbug_V1.0.0

ADD threadlocal-pratice-$version /home/project/threadlocal-pratice-$version

EXPOSE 8080

CMD ["java","-jar","/home/project/threadlocal-pratice-$version"]
